"""begin

Revision ID: 78b060d956ff
Revises: 
Create Date: 2024-06-20 09:59:52.899033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b060d956ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('Discriminator', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Наименование категории (заголовок)'),
    sa.Column('text', sa.String(), nullable=True, comment='Текст категории'),
    sa.Column('tree_header', sa.Boolean(), nullable=False, comment='Флаг вывода наименования категории с наименованием родителя'),
    sa.Column('page_size', sa.Integer(), nullable=True, comment='Количество кнопок на одной странице категории (при пагинации)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ownerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_category_id', sa.Integer(), nullable=False, comment='Категория, к которой отнесен элемент'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Отнесенная категория'),
    sa.Column('button_id', sa.Integer(), nullable=True, comment='Отнесенный элемент'),
    sa.Column('position_x', sa.Integer(), nullable=True, comment='Позиция элемента в категории (номер столбца)'),
    sa.Column('position_y', sa.Integer(), nullable=False, comment='Позиция элемента в категории (номер строки)'),
    sa.ForeignKeyConstraint(['button_id'], ['Buttons.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.ForeignKeyConstraint(['owner_category_id'], ['Categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ownerships')
    op.drop_table('Categories')
    op.drop_table('Buttons')
    # ### end Alembic commands ###
